
title: Hello and Welcome to the Stich N' Knitwhits Homepage!
description: We are a small business making all of our quality products by hand.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
